services:
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: ../docker/dev/app.dev.dockerfile
    ports:
      ["3000:3000"]
    volumes:
      - ../app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://api:4000
      NODE_ENV: development
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network-dev

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: ../docker/dev/api.dockerfile.dev
    ports:
      ["4000:4000"]
    volumes:
      - ../api:/usr/src/api
      - /usr/src/api/node_modules
    environment:
      DATABASE_URL: "postgres://prisma.ulabijgcrhzqudgtkqvp:xif17BzKKDJRAI8H@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x"
      NODE_ENV: development
    command: pnpm run start:dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network-dev

networks:
  app-network-dev:
    driver: bridge