services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      DIRECT_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_VERSION=${VITE_API_VERSION}
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge