services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./docker/prod/api.dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      DIRECT_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - app-network

  admin-site:
    container_name: admin-site
    build:
      context: ./admin-site
      dockerfile: ./docker/prod/admin-site.dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_API_URL: ${VITE_API_URL}
      VITE_API_VERSION: ${VITE_API_VERSION}
    networks:
      - app-network

  patients-site:
    container_name: patients-site
    build:
      context: ./patients-site
      dockerfile: ./docker/prod/patients-site.dockerfile
    ports:
      - "3001:3000"
    environment:
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_API_URL: ${VITE_API_URL}
      VITE_API_VERSION: ${VITE_API_VERSION}
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
      - admin-site
      - patients-site
    networks:
      - app-network

networks:
  app-network:
    driver: bridge