services:
  api:
    build:
      dockerfile: ./docker/dev/api.dockerfile.dev
    volumes:
      - ./api:/usr/src/api
      - /usr/src/api/node_modules
    environment:
      NODE_ENV: development
    command: pnpm run start:dev

  admin-site:
    build:
      dockerfile: ./docker/dev/admin-site.dockerfile.dev
    volumes:
      - ./admin-site:/usr/src/admin-site
      - /usr/src/admin-site/node_modules
    command: npm run dev
  patients-site:
    build:
      dockerfile: ./docker/dev/patients-site.dockerfile.dev
    volumes:
      -./patients-site:/usr/src/patients-site
      - /usr/src/patients-site/node_modules
    command: npm run dev