services:
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: ../docker/dev/app.prod.dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:4000
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: ../docker/dev/api.prod.dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgres://prisma.ulabijgcrhzqudgtkqvp:xif17BzKKDJRAI8H@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&supa=base-pooler.x"
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge