services:
  app:
    container_name: app
    build:
      context: ../app
      dockerfile: ../docker/dev/app.prod.dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:4000
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ../api
      dockerfile: ../docker/dev/api.prod.dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/ehr_manager?schema=public"
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ehr_manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge